# Violens are a powerful way to visualize the distribution of a feature across different categories (in this case, game modules).

import os
import glob
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

# Suppress warnings for cleaner terminal output
warnings.filterwarnings('ignore')

def compile_master_dataframe(processed_dir):
    """
    Hunts down all feature CSVs generated by Scripts 05, 06, 07, and 08,
    and merges them into a single master DataFrame for plotting.
    """
    print(f"🔄 Compiling master dataset from: {processed_dir}")
    games = ['TouchIt', 'CornerIt', 'DoubleTapIt', 'PinchIt', 'SlideIt', 'DragIt']
    all_games_data = []

    for game in games:
        # Find all feature files for this specific game
        ml_files = glob.glob(os.path.join(processed_dir, f"{game}_ML_Features.csv"))
        gaze_files = glob.glob(os.path.join(processed_dir, f"{game}_Gaze_Features.csv"))
        sync_files = glob.glob(os.path.join(processed_dir, f"{game}_Sync_Features.csv"))

        game_dfs = []
        
        if ml_files: game_dfs.append(pd.read_csv(ml_files[0]))
        if gaze_files: game_dfs.append(pd.read_csv(gaze_files[0]))
        if sync_files: game_dfs.append(pd.read_csv(sync_files[0]))

        if not game_dfs:
            continue

        # Merge all available feature dataframes for this game on Patient_ID and Game
        merged_game_df = game_dfs[0]
        for df in game_dfs[1:]:
            # Ensure we don't duplicate columns during merge
            cols_to_use = df.columns.difference(merged_game_df.columns).tolist() + ['Patient_ID', 'Game']
            merged_game_df = pd.merge(merged_game_df, df[cols_to_use], on=['Patient_ID', 'Game'], how='outer')

        all_games_data.append(merged_game_df)

    # Concatenate all games together into one long-form dataframe
    if all_games_data:
        master_df = pd.concat(all_games_data, ignore_index=True)
        return master_df
    else:
        return pd.DataFrame()

def generate_violin_plots(df, output_dir, features_to_plot):
    """
    Generates and saves a violin plot for each requested feature.
    """
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    # Set the visual style for clinical reporting
    sns.set_theme(style="whitegrid", palette="muted")

    for feature in features_to_plot:
        # Check if the feature actually exists in the compiled dataframe
        if feature not in df.columns:
            print(f"⚠️ Skipping '{feature}': Column not found in data.")
            continue
            
        # Drop NaN values for this specific feature so it doesn't break the plot
        plot_data = df.dropna(subset=[feature])
        
        if plot_data.empty:
            print(f"⚠️ Skipping '{feature}': All values are NaN.")
            continue

        plt.figure(figsize=(10, 6))
        
        # Create the Violin Plot
        # cut=0 prevents the violin tails from extending past the actual min/max data points
        # scale='width' makes all violins the same width, regardless of sample size
        ax = sns.violinplot(
            data=plot_data, 
            x='Game', 
            y=feature, 
            cut=0, 
            scale='width', 
            inner="quartile" # Shows lines for the median and interquartile ranges
        )
        
        # Add a swarmplot on top to show the actual individual patient data points
        sns.swarmplot(
            data=plot_data, 
            x='Game', 
            y=feature, 
            color="black", 
            alpha=0.5, 
            size=4
        )

        plt.title(f'Distribution of {feature} Across Games', fontsize=14, fontweight='bold')
        plt.xlabel('Game Module', fontsize=12)
        plt.ylabel(feature.replace('_', ' '), fontsize=12)
        plt.xticks(rotation=45)
        plt.tight_layout()

        # Save the plot
        safe_feature_name = feature.replace('/', '_')
        plot_path = os.path.join(output_dir, f"Violin_{safe_feature_name}.png")
        plt.savefig(plot_path, dpi=300)
        plt.close()
        
        print(f"✅ Saved plot: {plot_path}")

if __name__ == "__main__":
    PROCESSED_DIR = "gaze_analysis/data/processed/"
    PLOTS_DIR = os.path.join(PROCESSED_DIR, "plots")
    
    # 1. Compile all the data
    master_df = compile_master_dataframe(PROCESSED_DIR)
    
    if master_df.empty:
        print("❌ Could not find any processed feature CSVs to plot.")
    else:
        print(f"📊 Master DataFrame compiled with {len(master_df)} rows and {len(master_df.columns)} columns.")
        
        # 2. Define the exact features you requested to visualize
        target_features = [
            'Fixation_Count',
            'Mean_Fixation_Duration_sec',
            'Mean_Saccadic_Amplitude_cm',
            'Peak_Saccadic_Velocity_cm_s',
            'Saccade_Frequency_Hz',
            'Directional_Velocity_Alignment',
            'Mean_Action_Duration_sec',
            'Mean_Pressure_Overall',
            'Pressure_Jitter_Stationary',
            'Spatial_Jerk_Magnitude',
            'True_Eye_Hand_Latency_sec',
            'Accuracy_Ratio',
            'Correct_Taps',
            'Outside_Taps',
            'Number_of_Taps'
        ]
        
        # 3. Generate the plots
        print(f"\n🎨 Generating Violin Plots...")
        generate_violin_plots(master_df, PLOTS_DIR, target_features)
        
        print(f"\n🎉 All plots saved to: {PLOTS_DIR}")